import type { Metadata } from "next";
import "./globals.css";
import { NextUiProvider } from "@/utils/providers/NextUIProvider";
import NavBar from "./components/main/Navbar";
import "@radix-ui/themes/styles.css";
import { ScrollArea, Theme } from "@radix-ui/themes";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className=" bg-background">
      <body>
        <Theme>
          <ScrollArea className="bg-background "  type="always" scrollbars="vertical"   style={{ height: '100vh',  scrollbarColor: 'red'}}>
          <NavBar />
          <NextUiProvider>{children}</NextUiProvider>
          </ScrollArea>
        </Theme>
      </body>
    </html>
  );
}
